### ISSUE TITLE
Unicode Table significantly increases GPU load

### ISSUE THREAD

**Issue by Aflaris** [replaceitem/symbol-chat#45]
Opened up the Unicode Table on Minecraft version 1.21 for a minute and my GPU load skyrocketed (my gpu went from 30% to 60%). Probably due to loading all those complex characters all at once. Notably my CPU usage and memory were unaffected. Perhaps try limiting framerate, not rendering off-screen characters, or adding tabs to the table so not all characters are rendered at the same time. No big deal since I only use it for finding characters every once and a while but I'd call it a performance issue nonetheless.

**Comment by replaceitem** [comment]
Yea most of the render time is spent rendering the characters, but also some rendering the background squares.
The screen is already a bit optimized. There are no off screen characters being rendered, since when scrolling, all buttons are discarded and only for visible characters, new buttons are created.
However i can think of some way to improve performance further which i can implement:
* Instead of drawing background squares for each button, only draw a grid with lines which should be faster
* Toggle to render characters without shadow (should double performance)
* Render unicode block colors as larger rectangles
